### ISSUE TITLE
incompatibility with some stuff in gadgetsmenu

### ISSUE THREAD

**Issue by coolpvpv1** [LolGmar/Feedback#11]
heres the plugin first of all https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-14-4.10885/
now ill tell you what falses or is incompatiable i mean 
go into the gadgetmenu in the nether star go to gadgets go to fun & games click on the trampoline gadget and get a little flat area so you can put down the trampoline then when you spawn on it you false clip (phase) badpackets (timer) and normalmovements (unexpected y)  and it flags a ton ok heres another gadget that falses the anticheat go to the nether star go on gadgets go to mobs & npcs then choose when pigs fly gadget and when you fly around sometimes you false speed a and heres another gadget that falses the anticheat go to the gadgets menu go to movement on there and choose the rocket gadget you go to far down on your y in f3 like down to 100 so the rocket can go up and when the rocket goes away at the end in the air you get flagged down and you false fly (ascension) and nofall (packet) and when you hit players or mobs with the nether star it hits the mob and opens the gui so you false inventorymove (attacking) and thats all the gadgets i could find that false the anticheat you dont have to fix these but i thought i should report it sense alot of people use the gadgets menu plugin (actually over 132k people have downloaded and used this)

**Comment by LolGmar** [comment]
Well modified blocks that don't do it but i will add support for it later once add support for modified blocks
