### ISSUE TITLE
Vertialac Semi Anticheat Disabler LOL

### ISSUE THREAD

**Issue by coolpvpv1** [LolGmar/Feedback#40]
if you download gorillaglue b20 then turn on the module experimental then go on ladders or vines then turn on fly vanilla you can infinitly fly up and down and you can go to to side but its a little hard sense you still flag fly (float) so you have to keep moving up and down but its still infinite and its pretty op heres a video of it https://streamable.com/1e9qh its hard to do sideways but if you do it correctly you could fly infinitly

**Comment by LolGmar** [comment]
Exception cause if the player climbs adds a timer which stop it from false flagging
