### ISSUE TITLE
Bypasses (alot)

### ISSUE THREAD

**Issue by coolpvpv1** [LolGmar/Feedback#41]
client: Sensation b33 download https://files.catbox.moe/i0p9tx.rar
what bypasses is speed mode FMCHop you need speed 2 potion effect for it to go fast, Janitor sorta it only flags every like 5 seconds but its decent enough to speed up on players then turn it off in 5 seconds to not flag. slowhop, agc, pvpland, velt (use speed 2 potion effect) Jesus Mode FunkeMunky Works if the motion y is anything higher then 0.15 it pretty much works like 1.15 its op and sends you super high in the air xd Nofall Mode NoGround Works and thats it for today folks xd

**Comment by LolGmar** [comment]
Make sure that when you load it see if the checks are enable cause for me few were disable for some reasoning but next update should roll out few bug fixes and more checks for speed and fly bypassing and few packet checks if i have time

**Comment by coolpvpv1** [comment]
> Make sure that when you load it see if the checks are enable cause for me few were disable for some reasoning but next update should roll out few bug fixes and more checks for speed and fly bypassing and few packet checks if i have time

i went in the gui and enabled all the checks i remember doing that before i started recording
