### ISSUE TITLE
Speed A and C False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [LolGmar/Feedback#7]
go up like maybe 20 blocks then place a boat then go off the tower and sense the boats falling and makes you faster it will sometimes either false speed a or speed c

**Comment by LolGmar** [comment]
Wdym cause not flagging for me.

**Comment by coolpvpv1** [comment]
> Wdym cause not flagging for me.

https://streamable.com/o90i8

**Comment by LolGmar** [comment]
Look into it later.
discord Hell#6121 about your server
