### ISSUE TITLE
new and improved sigma vertical config

### ISSUE THREAD

**Issue by coolpvpv1** [LolGmar/Feedback#8]
delete the old config and put the new config in btw you can use phase on fencegates with hcf mode on and the distance set to anything from 0.8 to 3.0 it will flag phase a little bit but it still works so if there weren't staff on someone could phase into a players base but heres the download https://anonfile.com/w31ak430n0/vertical_txt sigmas cubecraft step at 1.5 blocks or 1.0 works btw

**Comment by LolGmar** [comment]
I know but flags for packets and block few more of sigma bypass soon
